# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=200, verbose_name='Slug')),
                ('vagas', models.IntegerField(verbose_name='Quantidade de vagas')),
            ],
        ),
    ]
