# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0002_auto_20160511_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='workshops',
            field=models.ManyToManyField(related_name='participantes', to='workshop.Workshop'),
        ),
    ]
